name: artificial-intelligence-gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.9
  - pytorch::pytorch=2.2.1
  - pytorch::pytorch-cuda=11.8
  - conda-forge::transformers
  - conda-forge::datasets
  - conda-forge::accelerate
  - conda-forge::bitsandbytes>0.37.0
  - scikit-learn
  - seaborn
  - pandas
  - nltk
